### ISSUE TITLE
Is it possible to export aard/slob database

### ISSUE THREAD

**Issue by Akbari694** [itkach/slob#1]
Dear all,
Is there a simple way to export the aard/slob database into an HTML formatted text file?

**Comment by Akbari694** [comment]
Thank you

**Comment by itkach** [comment]
It is possible to export individual blobs (content items) using slob command line interface (see https://github.com/itkach/slob/blob/master/README.org#command-line-interface), using `slob find` to identify content items and `slob get` to get actual content. It is also possible to explore slob content in a web browser with https://github.com/itkach/aard2-web and save content using browser's standard functionality. 

What are you trying to accomplish? I am not sure what "export the database into an HTML formatted text file" would mean - slobs may contain many items of different content types including various binary items, how (and why?) would you export all of this into a single HTML file?

**Comment by Akbari694** [comment]
Your aard2 app is excellent; but I need to have Wikipedia for an app like ColorDict so that I can use my dictionaries the same time. I have downloaded Wikipedia dump and converted it in a careless way. The result is not as perfect as Slob database.
I was looking for a way to convert slob database into an intermediate format(for example a text file) which I can handle.
I’m not sure what type of content “get” command will provide.
You should excuse me. I'm a beginner, not even familiar with python.

**Comment by itkach** [comment]
> what type of content “get” command will provide.

It gives you bytes. How those bytes should be interpreted is determined by content type. If you are to write a converter from slob to another format you need to use slob.py API to access it, command line interface is not designed for this.

> I was looking for a way to convert slob database into an intermediate format

slob file itself is a final product. Of course nothing prevents you from treating it as a data store (which it is) and converting to some other format or database, but in case of Wikipedia it is probably better to start with the data source used to create slobs: [mwscrape](https://github.com/itkach/mwscrape)'s [CouchDB](http://couchdb.apache.org) database. Take a look at https://github.com/itkach/mwscrape which downloads rendered articles HTML along with some metadata from Mediawiki API and how it is converted to slob (https://github.com/itkach/mwscrape2slob) or aar (https://github.com/itkach/aar2slob). There are plenty of ways to work with CouchDB - from ["raw" web API](https://wiki.apache.org/couchdb/HTTP_Document_API) to dedicated [CouchDB client libraries](https://wiki.apache.org/couchdb/Related_Projects) in various programming languages.

**Comment by AboRamy** [comment]
Hello @itkach 
Is it possible to extract slob files to html web pages with data folders?
Thanks for your help!
