### ISSUE TITLE
Temporary directory 

### ISSUE THREAD

**Issue by tinxx** [itkach/slob#11]
I suggest either using `pwd` or target directory also for temporary files *or* adding a parameter for changing the temporary directory.

---

Let's assume that people know best where there is enough space available on their device
and they probably point there with the output file(s) parameter.

As we are often working with huge files here (e.g. Wikipedia), there might *not* be enough space in the system `/tmp` directory.

Now, when you issue a command using `slob` it automatically creates a temporary directory, which is *not* located in the current work directory or next to the `slob` file you are working with but in the system `/tmp`.
That could lead to wasted hours when `/tmp` runs out of memory and `slob` aborts the current task with an `OSError: [Errno 28] No space left on device`.

**Comment by itkach** [comment]
Writer class takes `workdir` parameter. It is exposed as command line option in all converters including [mwscrape2slob](https://github.com/itkach/mwscrape2slob).

**Comment by tinxx** [comment]
It could help if parameter options were mentioned in `--help`.

**Comment by itkach** [comment]
It could, but apparently didn't :) try `slob convert --help`

**Comment by tinxx** [comment]
Bummer – thanks! :)
