### ISSUE TITLE
Library not loaded: libicui18n.54.dylib

### ISSUE THREAD

**Issue by brstream** [itkach/slob#12]
Thanks for the wonderful work with aard2. I was interested in using slob.py directly to look through a downloaded enwiki.slob file, but have not been able to get it running despite setting up numerous python virtualenv with the latest versions of icu and pyicu. The error I get is:

> Python 3.5.2 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:52:12)
> [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> \>>> import slob
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/.../anaconda/lib/python3.5/site-packages/slob.py", line 29, in <module>
>     import icu
>   File "/Users/.../anaconda/lib/python3.5/site-packages/icu.py", line 37, in <module>
>     from docs import *
>   File "/Users/.../anaconda/lib/python3.5/site-packages/docs.py", line 23, in <module>
>     from _icu import *
> ImportError: dlopen(/Users/.../anaconda/lib/python3.5/site-packages/_icu.cpython-35m-darwin.so, 2): Library not loaded: libicui18n.54.dylib
>   Referenced from: /Users/.../anaconda/lib/python3.5/site-packages/_icu.cpython-35m-darwin.so
>   Reason: image not found 

Not sure if I set up the environment correctly. Here is what I have installed:

> $ conda list
> \# packages in environment at /Users/brstream/anaconda/envs/env-slob:
> \#
> Using Anaconda Cloud api site https://api.anaconda.org
> icu                       56.1                          4    conda-forge
> openssl                   1.0.2h                        2
> pip                       8.1.2                    py35_0
> PyICU                     1.9.3                     <pip>
> python                    3.5.2                         0
> readline                  6.2                           2
> setuptools                25.1.6                   py35_0
> Slob                      1.0                       <pip>
> sqlite                    3.13.0                        0
> tk                        8.5.18                        0
> wheel                     0.29.0                   py35_0
> xz                        5.2.2                         0
> zlib                      1.2.8                         3
> (env-slob)

Thanks for your help.

Phap Luu

**Comment by itkach** [comment]
I'm not familiar with Anaconda, but this doesn't look right. Library file name `libicui18n.54.dylib` suggests that PyICU is built against ICU 54, but ICU 56 is installed.  I was able to set up working virtual env on El Capitan using [brew](http://brew.sh/) as described below.

- Install Python 3:
```
brew install python3
```
- Install ICU:
```
brew install icu4c
```

Note caveats:
```
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include
```

- Create virtual env and activate it:

```
python3 -m venv env-slob --system-site-packages
source env-slob/bin/activate
```
- Finally, with icu4c caveat in mind, install slob:

```
LDFLAGS=-L/usr/local/opt/icu4c/lib  CPPFLAGS=-I/usr/local/opt/icu4c/include pip3 install git+https://github.com/itkach/slob.git
```

- Check it:

```
python3 -m unittest slob
....................
----------------------------------------------------------------------
Ran 20 tests in 0.385s

OK
```

**Comment by itkach** [comment]
Closing for now since this doesn't seem to be an issue with the library itself.
