### ISSUE TITLE
cyclic reference for dict. download

### ISSUE THREAD

**Issue by strasz-li** [itkach/slob#18]
go to frontpage (http://aarddict.org/) -> click 'Dictionaries' -> click 'These are dictionaries for Aard 2 .' and it sends you back to the frontpage.

**Comment by itkach** [comment]
The link is "Aard 2" not entire phrase "These are dictionaries for Aard 2" and it point to the main site. I am not sure what's the problem and what would you like instead.

**Comment by strasz-li** [comment]
Thanks for the prompt response.

Let me explain myself: I thought that the sentence containing the link was
telling me I should click the link in order to go to the dictionaries'
download. Now I see that the sentence merely says about what's on the page
below it (which is the download page). It would be clearer to me if the
phrase was eg. "Below are dictionaries for Aard2." But it's just my
impression and I'm not a native English speaker anyway.

I've used previous version of Aard for a long time and I think you're doing
a great job. Cheers!

W.

2017-05-10 20:45 GMT+02:00 itkach <notifications@github.com>:
