### ISSUE TITLE
Unable to use eswiktionary-20170130.slob with aard2 v 0.35

### ISSUE THREAD

**Issue by 79453** [itkach/slob#19]
Hi, I have a Huawei P85 with android 5.01 and Aard2 and cannot use the eswiktionary-20170130.slob, have tried to download the file several times but Aard doesn't detect the file. I have no problem with other .slob files just this so far.
Sorry if this isn't the right place to describe this issue.

**Comment by itkach** [comment]
> Sorry if this isn't the right place to describe this issue.

It is not. This is issue tracker for software, not dictionary download issues.

> tried to download the file several times

Well, something is not working out. Verify that file is fully downloaded, saved with .slob extension, make sure size and hashsum matches what is posted on download page. I just downloaded on my phone - works fine here.
