### ISSUE TITLE
Feature request: in-app dictionary downloads

### ISSUE THREAD

**Issue by foolishgrunt** [itkach/slob#22]
Greetings, I'm a new user of Aard 2.

For reasons I don't care to explain here, I have disabled access to all web browsers on my phone. As such, the only way for me to download dictionaries for Aard is connect my phone to a desktop and transfer the files from there. This is not a huge inconvenience, though it is still an inconvenience. And so I ask: has it been considered to allow the Aard 2 app to download dictionary files from inside the app? Perhaps it could draw upon the list from the [wiki page](https://github.com/itkach/slob/wiki/Dictionaries).

I understand that my use case is unusual, so I apologize if this request comes across as self-serving. However, I could see it being a (small) benefit to other users as well, since it would simplify the setup process by not requiring any external applications as it does now.

Anyway, I got the idea from another app I use ([And Bible](https://github.com/mjdenham/and-bible)), which operates similar to the method I'm describing. That got me thinking that perhaps it's not so far-fetched after all.

**Comment by itkach** [comment]
> has it been considered to allow the Aard 2 app to download dictionary files from inside the app

Yes, it has, and the idea has been rejected. "to allow" is an interesting choice of words here - makes it sound like the ability is there and the app really doesn't mind doing it, but somebody just didn't permit it. That's not the case. Adding a built-in download manager is a sizeable project in itself. It adds considerable complexity to the codebase but very little functionality. How to download and move files around is fairly well understood and there are plenty of good tools to help, I see no need to try build another one.
