### ISSUE TITLE
Magnet link missing for dewiki-20181104-vol-0?.slob

### ISSUE THREAD

**Issue by mbe57** [itkach/slob#23]
Magnet link is missing for dewiki-20181104-vol-0?.slob, at least I cannot see it.

**Comment by itkach** [comment]
It is up to the person who created dictionary to decide how they want to share it. Not everything is distributed via bittorrent. dewiki-20181104-vol-0?.slob is available, as indicated, at http://ftp.halifax.rwth-aachen.de/aarddict/dewiki/ which is fast and reliable, why do you want magnet link? If you'd like to discuss this further - bring it up at the [forum](http://aarddict.org/forum).

**Comment by mbe57** [comment]
Yes, Igor, and I had hoped Martin would follow this site. Error on my part, this is about Aard2 itself ...
When it comes for RTWH versus Torrents: I see many peers in my torrent client that download from remote areas (different languages), with very limited total bandwidth. Some transfers took days until completion.
Those people may be the ones that need the Wikipedia most of all.
Hence my hope Martin will provide the Magnet Link (I sent him a direct mail, too).
TXs and have a good time and all the best for upcoming 2019
Michael
