### ISSUE TITLE
Direct download links to GDrive.

### ISSUE THREAD

**Issue by mahesh-hegde** [itkach/slob#24]
Google drive links posted here can be converted into direct download links by identifiying file id part and then,

`<base_url>/uc?id=<id>&export=download`

**Comment by Darthagnon** [comment]
Most of the download links on GDrive are blocked or dead. Guessing this project is dead, too? Are there copyright reasons the files can't also be mirrored on GitHub LFS and Archive.org, too?

**Comment by itkach** [comment]
Wiki page with dictionary links is community maintained. Users add or update links to dictionaries they compiled to wherever they chose to host the files. I guess Google Drive is one of the easiest ways to for people to share files, but these being personal and likely free accounts also not particularly. Most of the content typically comes from sources with permissive licenses that allow re-distribution so copyright reasons  are unlikely a factor.

Feel free to educate community and share suggestions at http://aarddict.org/forum/. (this issue tracker is for software issues)
