### ISSUE TITLE
Publish code onto PyPi

### ISSUE THREAD

**Issue by TAbdiukov** [itkach/slob#26]
I suggest 'slob' code to be published ontro PyPi. It eases up and opens up fo its reuse and hence improvements. 'slob' code is, for example, used in 'mwscrape2slob', however direct installation can be found frustrating with Slob not being on Pypi, and hence not installed with the usual setup.py

**Comment by vvasuki** [comment]
Now copied and published at https://pypi.org/project/dict-curation/0.0.2/ . Source here https://github.com/sanskrit-coders/dict-curation/tree/master/dict_curation/slob
