### ISSUE TITLE
Feature Request: Babylon .bgl to slob

### ISSUE THREAD

**Issue by azrdev** [itkach/slob#28]
On desktop, I'm happily using GoldenDict with the [free babylon dictionaries](https://www.babylon-software.com/free-dictionaries/languages/) for translation, and I'd like to use these with Aaard2 on mobile too.
AIUI there is no converter yet from bgl to slob, correct?
Maybe the easiest way to write one would be based on the [BGL](https://github.com/goldendict/goldendict/blob/master/bgl.cc)/[Babylon_BGL](https://github.com/goldendict/goldendict/blob/master/bgl_babylon.cc) parsing code of goldendict.

**Comment by itkach** [comment]
Quick search turns up https://github.com/ilius/pyglossary. Looks like it should be able to read .bgl and write .slob. Give it a try?

**Comment by azrdev** [comment]
Thanks for that idea, works like a charm! I only had to build pyglossary from master (<https://github.com/ilius/pyglossary/commit/ccbae3aa8c367e19c9144410a3e303b3e219c105> actually) because slob support is so new (https://github.com/ilius/pyglossary/issues/116) and not released yet.

Would you mind mentioning this somehow on https://github.com/itkach/slob/wiki/Dictionaries ?

**Comment by itkach** [comment]
Great!

> Would you mind mentioning this somehow on https://github.com/itkach/slob/wiki/Dictionaries ?

Updated README (since that's where the links to other converters are)
