### ISSUE TITLE
forum bug

### ISSUE THREAD

**Issue by OmlineEditor** [itkach/slob#29]
the forum ( http://aarddict.org/forum ) does not work correctly under some browsers. I only have a title without themes. please check the forum

**Comment by itkach** [comment]
Forum is just a [group in Google Groups](https://groups.google.com/forum/#!forum/aarddict). I don't control how and where it works . Works fine in Firefox and Chrome for me though. Perhaps you have an ad blocker/privacy extensions that may affect Google Groups operations. Should you decide to take this up with Google you may want to include details such as which browsers are "some browsers".
