### ISSUE TITLE
Adding dictionaries to slob wiki

### ISSUE THREAD

**Issue by yogiks** [itkach/slob#3]
@itkach 
Thanks for making this awesome tool and I have been using Aard for quite sometime and telling others about this and sharing the dictionaries.:)

I have [compiled a dictionary](http://goo.gl/GQeNVI) slob file for an Indian language, [Kannada](http://en.wikipedia.org/wiki/Kannada_language) from [wiktionary](kn.wiktionary.org) [xml dump](https://dumps.wikimedia.org/knwiktionary/latest/) which has more than [250 thousand](http://kn.wiktionary.org/wiki/%E0%B2%B5%E0%B2%BF%E0%B2%B6%E0%B3%87%E0%B2%B7:Statistics) articles/pages.  I would like to add this to the slob wiki here so that its easily accessible to all users of new Aard.

To do this, should I fork the wiki and send the pull request or it has to be done by any of the maintainers.? Please help. I would soon love to add other [Indian languages](http://en.wikipedia.org/wiki/National_language#India) as well. :)

Thanks. :)

**Comment by yogiks** [comment]
Couple of screenshots of my Aard 2 with Kannada wiktionary.:)

![kn-wiktionary-in-action-in-aard2](https://cloud.githubusercontent.com/assets/6291913/6144455/d99ab4f0-b1fd-11e4-88fa-6d3e2ecf66ed.png)
![kn-wiktionary-in-aard2](https://cloud.githubusercontent.com/assets/6291913/6144456/d99f4240-b1fd-11e4-9aaf-8c23d2f3e324.png)

**Comment by yogiks** [comment]
I just found I can edit it myself and (did this)[https://github.com/itkach/slob/wiki/Dictionaries/3c4ee0d03c589138ba806f4474cb08552a3ec5ae]. This is awesome.!

Thanks.:)

**Comment by itkach** [comment]
> Couple of screenshots of my Aard 2 with Kannada wiktionary.:)

Nice :)

> I can edit it myself

Indeed - any GitHub user can edit the wiki. So by all means - if you have something to share go ahead and add it :)
