### ISSUE TITLE
A suggestion about enwikionary20200615

### ISSUE THREAD

**Issue by sobaee** [itkach/slob#31]
Thank you for amazing work you are doing.

I just want to see the definitions or translation in english  language only (the size of slob file will be small, and the design will be small and easy to use).
But with this enwikionary I get the definition of a word in many languages beside english! (why? it's enwikionary!!)

I saw an english only enwikionary in another forum but it's older than yours (2019) and also fewer number of entries than yours.

Can you just redesign it to be english only translations?

**Comment by itkach** [comment]
Please post questions like these at http://aarddict.org/forum/

**Comment by itkach** [comment]
> But with this enwikionary I get the definition of a word in many languages beside english!

This is how wiktionaries work. Stripping out all non-english words and definitions is a lot of work and would limit usefulness of wiktionary to a wide audience. Space savings are not worth it. Consider using a different dictionary, such as [WordNet](https://github.com/itkach/slob/wiki/Dictionaries#wordnet) or [GCIDE](https://github.com/itkach/slob/wiki/Dictionaries#the-collaborative-international-dictionary-of-english-v051) - looks like they are exactly what you're looking for - English to English, small size.

**Comment by sobaee** [comment]
Thanks for the fast response

I agree with you that it will be a lot of work if anybody try to remove other languages from enwikionary, but I don't look for a dictionary like the tiny wordnet or even longman or oxford dictionaries which don't contain more than 200 thousand words!!

I look for this unbelievable dictionary which contains about **6.5 millions** words but in english language only (which could be about 3 or 4 millions words after removing the other languages), enwikionary is the vastest english-english dictionary ever.

As you said I will post this suggestion on aarddict.org forum if there is somebody wants to serve the humanity.

Greetings

**Comment by MHBraun** [comment]
The listed dictionaries are identical test versions with different compression ratios. The higher the compression the slower the access rate.Those versions will dissapear in the near future for gaining space.In order to extract the non english terms you could write a script to do it.-- Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 7/31/20, 13:26 sobaee <notifications@github.com> wrote:

   
  Thanks for the fast response 
  I agree with you that it will be a lot of work if anybody try to remove other languages from enwikionary, but I don't look for a dictionary like the tiny wordnet or even longman or oxford dictionaries which don't contain more than 200 thousand words!! 
  I look for this unbelievable dictionary which contains about 6.5 millions words but in english language only (which could be about 3 or 4 millions words after removing the other languages), enwikionary is the vastest english-english dictionary ever. 
  As you said I will post this suggestion on aarddict.org forum if there is somebody wants to serve the humanity. 
  Greetings

**Comment by sobaee** [comment]
@MHBraun 
Thanks, this was a valuable answer.

Can you help writing this script if you don't mind, and I will try to complete the process myself.

Iam just a normal python user, I can't write scripts, or if there a tool to be used for this purpose.
Many thanks 🙏

**Comment by sobaee** [comment]
I found and built this script "onlyen.py"

import nltk
words = set(nltk.corpus.words.words())
sent = "Io andiamo to the beach with my amico."
" ".join(w for w in nltk.wordpunct_tokenize(sent) \
if w.lower() in words or not w.isalpha())
# 'Io to the beach with my'


But when I try to run the script after I put it and the dictionary in the right directory no thing happens.

I tried this:
$ python onlyen.py enwiktionary-20200615-vol-01.txt enwiktionary-20200615-vol-01-1.txt
$

Then this:
$ python onlyen.py enwiktionary-20200615-vol-01.txt
$

How do I proceed after building the script?

Is there any issue the using of this sentence:  "Io andiamo to the beach with my amico."

Someone please?

**Comment by MHBraun** [comment]
Sorry I have no clue about phyton.But I would not use the slob database for this as you need to unpack every single blob in the slob file. Feasible but complicated. I would either use a download of the wikipedia content or as an alternative I can provide you with a couch database holding all articles.You could generate a modified couch version which would be the base of a new slob.Not sure, if someone else has a better idea....-- Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 7/31/20, 16:59 sobaee <notifications@github.com> wrote:

   
  I found and built this script "onlyen.py" 
  import nltk words = set(nltk.corpus.words.words()) sent = "Io andiamo to the beach with my amico." " ".join(w for w in nltk.wordpunct_tokenize(sent)  if w.lower() in words or not w.isalpha()) 
  'Io to the beach with my' 
  But when I try to run the script after I put it and the dictionary in the right directory no thing happens. 
  I tried this: $ python onlyen.py enwiktionary-20200615-vol-01.txt enwiktionary-20200615-vol-01-1.txt $ 
  Then this: $ python onlyen.py enwiktionary-20200615-vol-01.txt $ 
  How do I proceed after building the script? 
  Is there any issue the using of this sentence: "Io andiamo to the beach with my amico." 
  Someone please?

**Comment by MHBraun** [comment]
"Io andiamo to the beach with my amico."I do speak a little Italian. The sentence does say "I go to the beach with my friend"-- Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 7/31/20, 16:59 sobaee <notifications@github.com> wrote:

   
  I found and built this script "onlyen.py" 
  import nltk words = set(nltk.corpus.words.words()) sent = "Io andiamo to the beach with my amico." " ".join(w for w in nltk.wordpunct_tokenize(sent)  if w.lower() in words or not w.isalpha()) 
  'Io to the beach with my' 
  But when I try to run the script after I put it and the dictionary in the right directory no thing happens. 
  I tried this: $ python onlyen.py enwiktionary-20200615-vol-01.txt enwiktionary-20200615-vol-01-1.txt $ 
  Then this: $ python onlyen.py enwiktionary-20200615-vol-01.txt $ 
  How do I proceed after building the script? 
  Is there any issue the using of this sentence: "Io andiamo to the beach with my amico." 
  Someone please?
