### ISSUE TITLE
Spanish Wiktionary 

### ISSUE THREAD

**Issue by caralu74** [itkach/slob#32]
Thanks a lot for your dicts. I´ve downloaded the Spanish Wiktionary, but I see it is outdated, so How can I make a new updated one?

**Comment by erik55** [comment]
Also the Spanish Wikipedia is very outdated.

**Comment by MHBraun** [comment]
Correct.However not a topic for here...-- Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 8/10/20, 12:00 "☠☠☠" <notifications@github.com> wrote:

   
  Also the Spanish Wikipedia is very outdated.

**Comment by itkach** [comment]
As noted in README, https://github.com/itkach/mwscrape2slob is the tool to convert mediawiki sites to slob dictionaries.  Dictionary discussion are at http://aarddict.org/forum/

**Comment by caralu74** [comment]
Thank you so much for your answer. I will try it.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
