### ISSUE TITLE
Slob File format error in WIKI

### ISSUE THREAD

**Issue by tosbaha** [itkach/slob#33]
Hi,
I checked the WIKI for Slob File format and it says 

|  Element | Type  | Description  |
|---|---|---|
| content types  | char-sized sequence of content types  |MIME content types. Content items refer to content types by id.   |   
|   |   |  Content type id is 0-based position of content type in this sequence.|

However, when I checked a sample file I saw that size of content types is not char sized but short sized. 

Example **freedict-eng-tur-0.3.slob**
```
00000d8c  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000d9c  00 00 00 00 00 00 00 00  00 00 03 00 08 74 65 78  |.............tex|
00000dac  74 2f 63 73 73 00 16 61  70 70 6c 69 63 61 74 69  |t/css..applicati|
00000dbc  6f 6e 2f 6a 61 76 61 73  63 72 69 70 74 00 17 74  |on/javascript..t|
00000dcc  65 78 74 2f 68 74 6d 6c  3b 63 68 61 72 73 65 74  |ext/html;charset|
00000ddc  3d 75 74 66 2d 38 00 00  8e f0 00 00 00 00 00 0d  |=utf-8..........|
```

There are 3 content types. However, size of content is not 08 but instead **00 08** It is also same with others. Is there a typo in the WIKI? I checked the slob.py and it also says 

```python
 def read_text(self):
        return self._read_text(U_SHORT)

 def read_content_types():
        content_types = []
        count = f.read_byte()
        for _ in range(count):
            content_type = f.read_text()
            content_types.append(content_type)
        return tuple(content_types)
```

**Comment by itkach** [comment]
`00 08` is length (short-sized, 2 bytes) of the following character sequence `text/css`. `03` in `03 00 08` is the length of list of content types. I don't see an issue here.

**Comment by tosbaha** [comment]
Your documentation says **char-sized** for content_types. Char means a single byte, not 2 bytes. For example, tags are **char sized** and they are indeed char-sized which is a **single** byte.

**Comment by itkach** [comment]
There's length of list of content types (one byte) and then there's length of each individual content type entry. Number of different content types that can be contained in a slob file is char-sized, as in "you can have 255 of them", that's single byte "03". Content type itself is a piece of text of up to 2^16-1 length. That's specified as two bytes for length, followed by actual bytes that represent content type text; repeat for each entry in content type _list_

**Comment by tosbaha** [comment]
Let me try to explain my confusion in your documentation, with hex dumps. 
Tags are _char-sized sequence of tags_ meaning first number of tags comes and after that 1 byte for the length and the key of the tag. After that 1 byte(ff) size of tag value.

```
00000020  6c 69 62 0d 0e 76 65 72  73 69 6f 6e 2e 70 79 74  |lib..version.pyt|
00000030  68 6f 6e ff 33 2e 37 2e  32 2b 20 28 64 65 66 61  |hon.3.7.2+ (defa|
00000040  75 6c 74 2c 20 46 65 62  20 20 32 20 32 30 31 39  |ult, Feb  2 2019|
00000050  2c 20 31 34 3a 33 31 3a  34 38 29 20 20 5b 47 43  |, 14:31:48)  [GC|
00000060  43 20 38 2e 32 2e 30 5d  00 00 00 00 00 00 00 00  |C 8.2.0]........|
```

You see first comes `0D` which says there are 13 tags and then `0e` comes which says the value of the first tag has a length of 14. This is according to documentation which says **char-sized** sequence of tags' length is represented by a char which is a single byte. 

However, when it comes to content types, documentation still says **char-sized** sequence of content types. When we look at the hexdump,

```
00000da0  00 00 00 00 00 00 03 00  08 74 65 78 74 2f 63 73  |.........text/cs|
00000db0  73 00 16 61 70 70 6c 69  63 61 74 69 6f 6e 2f 6a  |s..application/j|
00000dc0  61 76 61 73 63 72 69 70  74 00 17 74 65 78 74 2f  |avascript..text/|
00000dd0  68 74 6d 6c 3b 63 68 61  72 73 65 74 3d 75 74 66  |html;charset=utf|
```

Hex dump says we have `03` content types. Which is OK. However, instead of starting with a char-sized content types, **short-sized** content types are listed. Instead of `08` we have `00 08` This is also the same for the next content type instead of `16` char sized we have `00 16` short sized. 

You said 

> Content type itself is a piece of text of up to 2^16-1 length. That's specified as two bytes for length, followed by actual bytes that represent content type text; repeat for each entry in content type list

In your documentation size of the tags and content types are both listed as char sized but one of them is char sized other one is short-sized.

element|type
----- | --
tags | char-sized sequence of tags
content types | char-sized sequence of content types

In your documentation short is written in 3 places.

**text**

short-sized sequence of encoded text bytes

**ref**
item index | short | Index of content item inside uncompressed bin

**short**

big endian unsigned short (2 bytes)


As you can see, you should either say content types are short sized, or you should say, content types are *text* instead of tiny-text as tags, so that I can understand the size of each content item.

**Comment by itkach** [comment]
I think you overlook this:
https://github.com/itkach/slob/blob/master/README.org#content-type

"content type" is basically an alias for "text".

**Comment by tosbaha** [comment]
My confusion was in your documentation, for `content type` it just writes `text`. It sounds like a placeholder in the documentation. For example, other sections of the format have tables and clearly shows **text** is a type. Maybe it is word it differently to clarify that content types are series of `text` instead of `tiny-text`
