### ISSUE TITLE
Links are dead in Arabic wiki

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [itkach/slob#35]
Hey, so i tried to download wiki Arabic with images (using torrent) and there is no peers so i think it's dead also i dont know why but i think all FTP server is empty ?

![Screenshot 2020-10-21 17:02:00](https://user-images.githubusercontent.com/28893833/96738612-2f68a300-13bf-11eb-9324-e0eb24dffb27.png)
![Screenshot 2020-10-21 17:02:12](https://user-images.githubusercontent.com/28893833/96738617-3099d000-13bf-11eb-8d20-448809dc82bd.png)

**Comment by MHBraun** [comment]
Correct. Server is down. All files are gone. We are rebuilding the server. Will take a couple of days.Please see google aarddict forum for updates.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 10/21/20, 10:02 Esmail EL BoB <notifications@github.com> wrote:

   
  Hey, so i tried to download wiki Arabic with images (using torrent) and there is no peers so i think it's dead also i dont know why but i think all FTP server is empty ?

**Comment by EsmailELBoBDev2** [comment]
Alright, Thanks!

**Comment by mbe57** [comment]
Esmail, the server storyge broke at RWTHand they are rebuilding over time.
Cheers
Michael


Esmail EL BoB <notifications@github.com> schrieb am Mi., 21. Okt. 2020,
17:02:
