### ISSUE TITLE
Tamil Wiktionary download link is not working.

### ISSUE THREAD

**Issue by ArunHackers** [itkach/slob#36]
(Not Found
The requested URL was not found on this server.)
This error found to when I tried to download this file:

Tamil
file:	tawiktionary-20200104.slob
size:	0.54 GiB
sha1:	in tawiktionary-20200104.slob.sha
url:	http://ftp.halifax.rwth-aachen.de/aarddict/tawiki/
note:	Dictionary does support LZMA2 compression, external picture download, language links, geo links.
note:	Maintainer: AardFeed at web.de
note:	Questions: https://groups.google.com/forum/#!forum/aarddict
note:	Thanks to RWTH Aachen University https://www.rwth-aachen.de/ for high speed mirroring

Please fix the problem. Kindly upload the file to Google Drive. Thank you.

**Comment by MHBraun** [comment]
This is correct. With the loss of the database I am updating only
dictionaries which are requested.

The new update is here:

http://ftp.halifax.rwth-aachen.de/aarddict/tawiki/

Please direct all dictionary question to

https://groups.google.com/forum/embed/#!forum/aarddict

Thank you

Markus

**Comment by ArunHackers** [comment]
Yeah I'll ask any information related on dictionary in group. Thank you.

**Comment by ArunHackers** [comment]
Hello sir kindly join me in the google group. I request you SLOB file for TAMIL WIKIPEDIA (2020 update). Thank you 🙏
