### ISSUE TITLE
Please Update Wikitionary For Hindi and Malayalam 

### ISSUE THREAD

**Issue by shockergit** [itkach/slob#37]
The slab file is almost 5 years old. It would have been great if you pull an update. Thanks

**Comment by francwalter** [comment]
Am I wrong, that Hindi and Malayalam are two totally different languages?
And it is slob, not slab :)
If you give me the link for them both, I will try to scrape them.

**Comment by shockergit** [comment]
Lol sorry it was slob😇. And yes it is two different languages
Malayalam link https://ml.m.wiktionary.org/wiki/പ്രധാന_താൾ
Hindi link https://hi.m.wiktionary.org/wiki/मुखपृष्ठ

**Comment by shockergit** [comment]
Thank you

**Comment by francwalter** [comment]
Ok then, see the communication in the groups: [Wikitionary update for Hindi and Malayalam Please](https://groups.google.com/g/aarddict/c/daK7ZTGUFjY/m/WIx-G31oDAAJ)
