### ISSUE TITLE
Update slob download links

### ISSUE THREAD

**Issue by Tarek-Hasan** [itkach/slob#42]
Please, update these following dictionaries.
- WordNet version is currently 3.1 which is last updated 2011 and now unmaintained. [Open English WordNet](https://github.com/globalwordnet/english-wordnet) is an actively maintained fork of Princeton WordNet, which just released its 2022 Edition in 31st December 2022.
- Simple English Wiktionary link is invalid and also last updated in 2020.
- Arabic Wiktionary last updated in 2020.
- Bengali Wiktionary link is invalid and also last updated in 2016.
- Korean and Japanese Wiktionary last updated in 2015.
- Wikispecies last updated in 2020 and link also invalid.
- Collaborative International Dictionary of English (GCIDE) version is 0.52, where latest version is 0.53.
- [CC-CEDICT](https://www.mdbg.net/chinese/dictionary?page=cedict) last updated 2021, newer version has 2,425 more entries.

**Comment by MHBraun** [comment]
There is no dedicated maintainer for this area. The files are generated from different enthusiasts.

Pls check
Ftp://halifax.rwth-aachen.de/aarddict
For updated versions regulary as noted.

You may generate some dictionaries as well and publish thise here.

Markus


________________________________
From: Tarek Hasan Faruk ***@***.***>
Sent: Thursday, January 19, 2023 17:38
To: itkach/slob
Cc: Subscribed
Subject: [itkach/slob] Update slob download links (Issue #42)

Please, update these following dictionaries.
WordNet version is currently 3.1 which is last updated 2011 and now unmaintained. Open English WordNet is an actively maintained fork of Princeton WordNet, which just released its 2022 Edition in 31st December 2022.
Simple English Wiktionary link is invalid and also last updated in 2020.
Arabic Wiktionary last updated in 2020.
Bengali Wiktionary link is invalid and also last updated in 2016.
Korean and Japanese Wiktionary last updated in 2015.
Wikispecies last updated in 2020 and link also invalid.
Collaborative International Dictionary of English (GCIDE) version is 0.52, where latest version is 0.53.
CC-CEDICT last updated 2021, newer version has 2,425 more entries.

**Comment by itkach** [comment]
@Tarek-Hasan Thank you for the report and suggestions. I cleaned up the wiki and removed broken links. As @MHBraun said, this is community managed page, no guarantee that folks who compiled dictionaries and shared links at some point are willing or able to do so continuously, so maintenance is "best effort". 

Taking a quick look at Open English WordNet, it appears that the data is available in WordNet database format, so perhaps existing converter https://github.com/itkach/wordnet2slob can be applied. I don't know who converted CC-CEDICT originally and how they did it, so can't help here.

Note that this is repository for slob file format and reference implementations, best place for dictionaries related discussions is aarddict Google group at https://groups.google.com/g/aarddict

**Comment by itkach** [comment]
> * [Open English WordNet](https://github.com/globalwordnet/english-wordnet) is an actively maintained fork of Princeton WordNet, which just released its 2022 Edition in 31st December 2022.

here: https://github.com/itkach/slob/wiki/Dictionaries#open-english-wordnet
