### ISSUE TITLE
Add new dictionary

### ISSUE THREAD

**Issue by Tarek-Hasan** [itkach/slob#43]
Please add [FOLDOC](https://foldoc.org/) computing dictionary.
Dictionary source:
https://foldoc.org/source.html

**Comment by MHBraun** [comment]
This could be your first project.

However please mive over to the google aarddict group. There is the correct place to discuss.

This is not a software issue with the program.


Markus

________________________________
From: Tarek Hasan Faruk ***@***.***>
Sent: Friday, January 20, 2023 18:47
To: itkach/slob
Cc: Subscribed
Subject: [itkach/slob] Add new dictionary (Issue #43)

Please add FOLDOC computing dictionary.
Dictionary source:
https://foldoc.org/source.html

**Comment by itkach** [comment]
[FOLDOC](https://foldoc.org/) looks like good content under permissive license. Of course somebody would need to write a custom converter to converted to .slob. Could be a good project, but is out of scope for this repo :)
