### ISSUE TITLE
Add updated dictionary

### ISSUE THREAD

**Issue by Tarek-Hasan** [itkach/slob#46]
I updated two dictionaries, which can be found [here](https://github.com/Tarek-Hasan/Multilingual-Dictionaries/releases)
- CC-CEDICT 2023.03.11
- JMdict (Japanese-Multilingual Dictionary) with examples 2023.03.11

I also wanted to update [GCIDE](https://gcide.gnu.org.ua) (GNU Collaborative International Dictionary of English) to latest version. [Here](https://www.ibiblio.org/webster/) I found an XML format of the dictionary, but don't know how to work with split XML. I would appreciate some help.

**Comment by itkach** [comment]
- add your link at https://github.com/itkach/slob/wiki/Dictionaries (any github user can edit)
- please move any other discussions/questions to https://groups.google.com/g/aarddict

Thank you.
