### ISSUE TITLE
BUG: Alias cannot point to several blobs

### ISSUE THREAD

**Issue by soshial** [itkach/slob#49]
**Description**
According to your [answer](https://github.com/itkach/slob/issues/27#issuecomment-489431778) in another issue:
> > **@LRN**: Does SLOB allow aliases to point to multiple entries?
>
> **@itkach**: Sort of. Each key points to one blob, but you can add the same key multiple times (each time pointing to different content). Some data sources may have multiple different articles for the same word, e.g. different meanings of "A". When converting to slob, you can add each one separately with the same key "A" (of course you can also chose to combine the articles into one). Others, like Wikipidea, usually have "disambiguation" pages, so a generic term that can have a lot of different meanings is associated with a single page that has a collection of links to more specific terms.

I tried to create a Slob dictionary with a lot of aliases (that can collide for different words). For example: "клея" should point to "клеить" (v.) and to "клей" (n.). But whenever I add alias via `add_alias()` for the same target key, only the first one works.

**To Reproduce**
```python
	with slob.create(filepath) as writer:
		writer.add(
			"This is a definition for Word 1".encode("ascii"),
			"word1", "alias_that_points_to_several_blobs",
			content_type=slob.MIME_TEXT,
		)
		writer.add(
			"This is a definition for Word 2".encode("ascii"),
			*("word2", "alias_that_points_to_several_blobs"),
			content_type=slob.MIME_TEXT)

		writer.add_alias("this_alias_cannot_point_to_several_blobs", "word1")
		writer.add_alias("this_alias_cannot_point_to_several_blobs", "word2")
```

(**CORRECT**) When user enters `alias_that_points_to_several_blobs` both entries are shown:

<img width="1248" alt="Screenshot 2024-04-14 at 14 39 17" src="https://github.com/itkach/slob/assets/100644/a7582c47-bbca-4ca7-b407-3c2c096310c7">

(**INCORRECT**) When user enters `this_alias_cannot_point_to_several_blobs`, both aliases should be shown in the list:

<img width="1374" alt="Screenshot 2024-04-14 at 14 39 45" src="https://github.com/itkach/slob/assets/100644/5dd7c91c-fe9d-4d6f-98b4-5c8694caff8f">

**Expected behavior**
When user enters `this_alias_cannot_point_to_several_blobs`, **both aliases should be shown** in the list.

**Environment:**
 - OS: macOS
 - Python version: 3.9

**Comment by itkach** [comment]
fixed in 5a3758f282340be8ff8123d79c4435677dc73bb6

**Comment by soshial** [comment]
Thank you so much, @itkach, for such a lightning-fast answer and a fix!
Although, I am really surprised I was the first one, who noticed the bug.

**Comment by soshial** [comment]
There is another problem, if you run this code:

```python
with slob.create(filepath) as writer:
    writer.add(
        "This is a definition for Word 1".encode("ascii"),
        "word1", "alias_to_word1_and_word2",
        content_type=slob.MIME_TEXT,
    )
    writer.add(
        "This is a definition for Word 2".encode("ascii"),
        *("word2", "alias_to_word1_and_word2"),
        content_type=slob.MIME_TEXT)

    writer.add_alias("2nd_order_alias_must_point_to_both_word1_and_word2", "alias_to_word1_and_word2")
```

Then, while searching for the 2nd-order alias, it will point only to word1:

<img width="1481" alt="Screenshot 2024-04-14 at 22 21 34" src="https://github.com/itkach/slob/assets/100644/b9d3f9a1-38fa-4561-abfd-2b176c60b38d">

It should point to both word1 and word2 by transitivity:

<img src="https://github.com/itkach/slob/assets/100644/8f6d32f3-6444-4ac8-9ace-1ff01cfcd343" width=400 />

**Comment by itkach** [comment]
> I am really surprised I was the first one, who noticed the bug.

Well, this is a somewhat atypical case. Primary use case I had in mind was implementing http-style redirects that existed in  Wikipedia markup (in the early days we used to parse Mediawaki's XML dump which contained articles in Mediawiki markup which was parsed with [mwlib](https://github.com/pediapress/mwlib), and redirects can only ever point to one thing. Having multiple occurrences of the same key pointing to different articles is also rare - typically in a dictionary all the different meanings for a word would be combined into a single article, although I've seen it in some dictionaries. Now, of course slob being a list allows duplicate keys, and adding multiple keys pointing to the same content either right away or later via `add_alias` should yield the same result - which I believe this fix achieves. Resolving multi-level multi-target redirects is quite something else though. I think implementing redirect-like multi-level alias resolution in this library was a mistake - it is complex, is not part of slob format itself in any way, and none of contemporary available data sources - Mediawiki via API, Mediawiki via enterpirse html dump, xdxf, tei, wordnet - require or benefit from it. Complex alias/redirect resolution can and should be implemented (if necessary) outside of this library.
