### ISSUE TITLE
French Wiktionary link points to wrong/damaged file

### ISSUE THREAD

**Issue by pachtchenko** [itkach/slob#5]
In <a href = "https://github.com/itkach/slob/wiki/Dictionaries#french-1">French Wiktionary</a> section, the <a href="https://drive.google.com/file/d/0B8ENyWhpePB8Um05dFdLemNWbG8/view?usp=sharing">link</a> points to a file with wrong SHA1 and size (285,147,136 instead of 405,635,161 bytes). The file looks damaged (GoldenDict does not detect it)

**Comment by itkach** [comment]
I re-uploaded the file and updated link, give it a try

**Comment by pachtchenko** [comment]
It works, thanks a lot!
