### ISSUE TITLE
After icu update to 75.1 slob load failure

### ISSUE THREAD

**Issue by awkiw** [itkach/slob#51]
![20240505_043642NSLOB](https://github.com/itkach/slob/assets/165974210/56d377fa-fa23-4ebb-ad0d-d0368ebbf992)
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29562
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
14
Kernel build information:
Linux localhost 4.19.191-28086179-abT225XXU6DWL9 #1 SMP PREEMPT Wed Dec 20 16:55:14 +07 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T225
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.styling versionCode:31

**Comment by awkiw** [comment]
beautifulsoup4     4.12.3
certifi            2024.2.2
charset-normalizer 3.3.2
colorama           0.4.6
html5lib           1.1
icu                0.0.1
idna               3.7
jsonstrip          22.10.20
lxml               5.2.1
pip                24.0
prompt-toolkit     3.0.43
pyglossary         4.6.1
PyICU              2.13
python-idzip       0.3.9
requests           2.31.0
six                1.16.0
Slob               1.0.2
soupsieve          2.5
termuxgui          0.1.6
urllib3            2.2.1
wcwidth            0.2.13
webencodings       0.5.1

**Comment by awkiw** [comment]
Python 3.11.8 (main, Feb 11 2024, 13:05:24) [Clang 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d1 on linux

**Comment by itkach** [comment]
After icu update you have to rebuild PyICU against new icu libraries. This is just how it works, it's not an issue with slob or PyICU.
