### ISSUE TITLE
Adding a label does not work

### ISSUE THREAD

**Issue by Snaptags** [itkach/slob#7]
I'm trying to add a label to a already created slob file:
```
slob tag -n label -v "A Fine Dictionary" my.slob
```
All I get is a "No such tag" error.

```
slob info my.slob
TAGS
----
    created.at: 2015-03-31T10:47:43.771907+00:00
   version.icu: 54.1
version.python: 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
 version.pyicu: 1.8
```

How do I ADD new tags?

Without the "label" tags my slobs are displayed as "???" in the android client :-(

**Comment by itkach** [comment]
Tag value can be modified with the `slob tag` command, but tag needs to already exist.
Tags, like content, can only be added when dictionary is being created (by calling [tag(name, value) method](https://github.com/itkach/slob/blob/master/slob.py#L875)). Here's an example: https://github.com/itkach/mwscrape2slob/blob/master/mwscrape2slob/__init__.py#L778

**Comment by Snaptags** [comment]
Thank you for the sample! My converter works perfectly now and I enjoy the new version on Android

**Comment by qoheniac** [comment]
So what is the easiest way to add a tag to an existing slob. I need to open the old one, create a new one, copy everything and add the new tag, I guess. But how is this done most efficiently?
